"""empty message

Revision ID: d11bc4ca1a58
Revises: d4c5e74bac8a
Create Date: 2021-08-24 10:13:32.743144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11bc4ca1a58'
down_revision = 'd4c5e74bac8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrivi_pagamenti',
    sa.Column('id_ArriviPagamenti', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_prenotazione', sa.Integer(), nullable=True),
    sa.Column('pagamento', sa.Integer(), nullable=True),
    sa.Column('dataPagamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_prenotazione'], ['arrivi.id_arrivo'], ),
    sa.PrimaryKeyConstraint('id_ArriviPagamenti'),
    sa.UniqueConstraint('id_ArriviPagamenti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrivi_pagamenti')
    # ### end Alembic commands ###
