"""empty message

Revision ID: d4c5e74bac8a
Revises: eb8e2e99ae9a
Create Date: 2021-08-24 10:03:11.842591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c5e74bac8a'
down_revision = 'eb8e2e99ae9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrivi_extra', sa.Column('prezzo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arrivi_extra', 'prezzo')
    # ### end Alembic commands ###
